title: Simon Sickle
email: sickle@hey.com
twitter_username: SickleTech
github_username:  simonsickle

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed
  load_paths:
    - _saas
    - node_modules
